perpuskita/urls.py

from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from. import views

urlpatterns = [
    path('home/', views.home),
    path('admin/', admin.site.urls),
    path('', include('perpustakaan.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perpustakaan/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from. import views

app_name = 'perpustakaan'

urlpatterns = [
    path('formuser', views.form_user_sss, name='formuser'),
    path('formpinjam/', views.formpinjam, name='formpinjam'),
    path('formbuku/', views.formbuku , name='formbuku'),
    path('list_pinjaman/', views.daftarpinjam , name='list_pinjam'),
    path('list_mahasiswa/', views.daftarmhs, name='list_mhs'),
    path('list_buku/', views.daftarbuku , name='list_buku'),
    path('form_mhs/', views.form_mahasiswa, name='formmhs'),
    path('hapusbuku/<str:idbuku>', views.hapusbuku , name='hapusbuku'),
    path('hapuspinjam/<str:idpinjam>', views.hapuspinjam , name='hapuspinjam'),
    path('hapusmhs/<str:npm>', views.hapusmhs , name='hapusmhs'),
    path('editmhs/<str:npm>', views.editmhs , name='editmhs'),
    path('editbuku/<str:idbuku>', views.editbuku , name='editbuku'),
    path('lihatbuku/<str:idbuku>', views.lihatbuku , name='lihatbuku'),
    path('lihatmhs/<str:npm>', views.lihatmahasiswa , name='lihatmhs'),
    path('logout/', views.logoutuser, name='logout'),
    path('', views.login_user, name='login'),
    path('perpuskita/',views.index, name='index'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

perpustakaan/models.py
from asyncio.windows_events import NULL
from distutils.command.upload import upload
from urllib.parse import MAX_CACHE_SIZE
from django.db import models
from datetime import datetime,timedelta

# Create your models here.
class buku(models.Model):
    kat = [
        ('Edukasi', 'Edukasi'),
        ('entertainment', 'Entertainment'),
        ('Komik', 'Komik'),
        ('Biografi', 'Biografi'),
        ('Sejarah', 'Sejarah'),
        ('Novel', 'Novel'),
        ('scifi','Sci-Fi')
        ]
    idbuku = models.CharField(max_length=255, primary_key=True)
    judul = models.CharField(max_length=255)
    pengarang = models.CharField(max_length=255)
    kategori = models.CharField(max_length = 255, choices = kat )
    sinopsis = models.CharField(max_length=255)
    tahunterbit = models.CharField(max_length=255)
    penerbit = models.CharField(max_length=255)
    cover = models.ImageField(upload_to='media/', max_length=255, null = True, blank = True)       
    def __str__(self):
        return "{} - {} ".format(self.idbuku, self.judul, self.pengarang)
        return self.idbuku
    class Meta:
        db_table = "myapp_image"

class mahasiswa(models.Model):
    jur = [
        ('Teknik Informatika', 'Teknik Informatika'),
        ('Sistem Informasi', 'Sistem Informasi'),
        ('Keperawatan', 'Keperawatan'),
        ('Pertanian', 'Pertanian'),
    ]
    npm = models.CharField(max_length=255, primary_key=True)
    nama = models.CharField(max_length=255 )
    jurusan = models.CharField(max_length=255, choices= jur)
    no_hp = models.CharField(max_length=255 )
    no_ktp = models.CharField(max_length=255)
    alamat = models.CharField(max_length = 255)
    foto = models.ImageField(upload_to='media/' , max_length=255, blank=True, null=True)
    def __str__(self) -> str:
        return "{} - {}".format(self.npm, self.nama, self.jurusan)

def balik():
    return datetime.today() + timedelta(days=14)
class pinjam(models.Model):
    idpinjam = models.AutoField( primary_key=True)
    npm = models.ForeignKey(mahasiswa, on_delete= models.CASCADE)
    idbuku = models.ForeignKey(buku, on_delete= models.CASCADE)
    tanggal = models.DateField(auto_now_add=True)
    kembali = models.DateField(default = balik)

    def __str__(self) -> str:
        return "{} - {} -{} - {}".format(self.idpinjam, self.tanggal, self.idbuku, self.npm)

perpustakaan/forms.py
from dataclasses import fields
from pyexpat import model
from statistics import mode
from django import forms
from.models import buku, mahasiswa, pinjam
from django.contrib.auth.models import  Group, User

class form_mhs(forms.ModelForm):
    class Meta:
        model = mahasiswa
        fields = "__all__"
        
class Form_buku(forms.ModelForm):
    class Meta:
        model = buku
        fields = "__all__"

class Form_pinjam(forms.ModelForm):
    class Meta:
        model = pinjam
        fields = "__all__"
        
class Form_user(forms.ModelForm):
    class meta:
        model = User
        fields = "__all__"

perpustakaan/views.py

from xml.etree.ElementInclude import include
from django.shortcuts import render, redirect
from .forms import Form_buku, Form_pinjam, Form_user, form_mhs, form_mhs
from perpustakaan.models import buku ,mahasiswa , pinjam
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth import authenticate , login, logout
from django.contrib.auth.models import  Group
import perpustakaan

# Create your views here.

#dashboard_
def index(request):
    testgrup = Group.objects.get(name='super admin')
    gr = request.user.groups.all()
    grp = None
    if testgrup in gr:
        grp = "Super Admin"
        navbar = "perpustakaan/navbaradmin.html"
    else: 
        grp = " Operator"
        navbar = "perpustakaan/navbar.html"
    return render(request,'perpustakaan/index.html', {'grp':grp , 'navbar':navbar} )

#daftarbuku
def daftarbuku(request):
    bk = buku.objects.all()
    context ={
        
        'daftar_buku': bk,
    }
    return render(request, 'perpustakaan/daftarbk.html' ,context)

#Daftar mahasiswa
def daftarmhs(request):
    mhs = mahasiswa.objects.all()
    context ={
        
        'data': mhs,
    }
    return render(request, 'perpustakaan/daftarmahasiswa.html' ,context)

#daftar pinjaman buku
def daftarpinjam(request):
    list_pinjam = pinjam.objects.all()

    context = {
       'pinjam' : list_pinjam,
    }
    return render(request, 'perpustakaan/daftarpinjam.html', context)

#form pengisian mahasiswa
def form_mahasiswa(request):
    mahasiswa_form = form_mhs(request.POST or None)
    if request.method == 'POST':
        mahasiswa_form = form_mhs(request.POST, request.FILES)
        if mahasiswa_form.is_valid():
            mahasiswa_form.save()
            img = mahasiswa_form.instance
            messages.success(request, "Mahasiswa Berhasil Di tambahkan", {'img': img})
            
            return redirect ('/form_mhs')
        else:
            messages.error(request, "Gagal Menambahkan Mahasiswa")
    context = {

        'form': mahasiswa_form,
    }

    return render(request, 'perpustakaan/mhsform.html', context)

#form pengisisan buku
def formbuku (request):
    formbk = Form_buku(request.POST or None)
    if request.method == 'POST':
        formbk = Form_buku(request.POST, request.FILES)
        if formbk.is_valid():
            formbk.save()
            img_obj = formbk.instance
            messages.success(request, "Buku Berhasil Di tambahkan")
            return redirect('/formbuku', {'omg_obj' : img_obj})
        else:
            messages.error(request, "Gagal Menambahkan Buku")
    context = {
        'buku': formbk,
    }
    return render(request, 'perpustakaan/formbuku.html' , context)
    
def formpinjam (request):
    formpj = Form_pinjam(request.POST or None)
    if request.method == 'POST':
        if formpj.is_valid():
            formpj.save()
            messages.success(request, "Pinjaman Berhasil Di tambahkan")
            return redirect('/formpinjam')
        else:
            messages.error(request, "Gagal menambahkan Pinjaman")
            return redirect('/formpinjam')
    context = {
        'pinjam': formpj,
    }
    return render(request, 'perpustakaan/formpinjam.html' , context)

def hapusbuku(request,idbuku):
    delbuku = buku.objects.get(idbuku = idbuku)
    delbuku.delete()
    return redirect('/list_buku')

def hapuspinjam(request,idpinjam):
    delpinjam = pinjam.objects.get(idpinjam = idpinjam)
    delpinjam.delete()
    return redirect('/list_pinjaman')

def hapusmhs(request,npm):
    delmhs = mahasiswa.objects.get(npm = npm)
    delmhs.delete()
    return redirect('/list_mahasiswa')
    
def login_user(request):
    context = {
        
    }
    if request.method == 'POST':
        userna = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=userna, password=password)
        context = {
            "login": user
        }
        if user is not None:
            login(request, user)
            return redirect('/perpuskita')

        else : 
            messages.error(request, 'username atau password yang anda masukkan salah')          
            return redirect('/')

    return render(request, 'perpustakaan/login.html')

def logoutuser(request):
    if request.method == "POST":
        logout(request)
        return redirect('/')

    return render(request ,'perpustakaan/logout.html')

def editmhs(request, npm):
    editmaha = mahasiswa.objects.get(npm = npm)
    context = {'editmhs': editmaha}
    updatemhs = form_mhs(request.POST, instance=editmaha)
    if updatemhs.is_valid():
        updatemhs.save()
        messages.success(request, 'update mahasiswa berhasil')

    return render(request ,'perpustakaan/editmhs.html', context)

def editbuku(request, idbuku):
    editbk = buku.objects.get(idbuku = idbuku)
    context = {'editbuku': editbk}
    updatebk = Form_buku(request.POST, instance=editbk)
    if updatebk.is_valid():
        updatebk.save()
        messages.success(request, 'update Buku berhasil')

    return render(request ,'perpustakaan/editbuku.html', context)

def lihatbuku(request,idbuku):
    lihatbk = buku.objects.get(idbuku=idbuku)
    context = {'lihatbuku': lihatbk}

    return render(request, 'perpustakaan/lihatbuku.html', context)

def lihatmahasiswa(request,npm):
    lihatmhs = mahasiswa.objects.get(npm = npm)
    img_obj = request
    context = {'lihatmhs': lihatmhs}
    return render(request, 'perpustakaan/lihatmhs.html', context)

def form_user_sss(request):
    formuser = Form_user(request.POST or None)
    if request.method == 'POST':
        formuser = Form_user(request.POST)
        if formuser.is_valid():
            formuser.save()
            messages.success(request, "Berhasil menambahkan")
            return redirect('/formbuku')
        else:
            messages.error(request, "Gagal Menambahkan")
    context = {
        'user': formuser,
    }
    return render(request, 'perpustakaan/formuser.html' , context)

perpustakaan/templates/perpustakaan/daftar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <style>
            /* (A) GLOBAL */
* {
  font-family: arial, sans-serif;
  box-sizing: border-box;
}
body {
  display: flex;
  min-height: 100vh;
  padding: 0; margin: 0;
}

/* (B) SIDEBAR */
/* (B1) SIDEBAR ITSELF */
#pgside {
  width: 200px;
  transition: width 0.2s;
  background: #283039;
}

/* (B2) USER OR BRANDING */
#pgside #pguser {
  display: flex;
  align-items: center;
  padding: 10px 5px;
}
#pgside #pguser img {
  width: 50px;
  margin-right: 5px;
  border-radius: 50%
}

/* (B3) SIDEBAR ITEMS */
#pgside, #pgside a { color: #fff; }
#pgside a {
  display: block;
  padding: 20px;
  width: 100%;
  text-decoration: none;
  cursor: pointer;
}
#pgside a.current { background: #7c1919; }
#pgside a:hover { background: #9b2323; }

/* (B4) SIDEBAR ICONS & TEXT */
#pgside i.ico, #pgside i.txt { font-style: normal; }
#pgside i.ico {
  font-size: 1.1em;
  margin-right: 10px;
}

/* (B5) SMALL SCREEN TRANSFORMATION */
@media screen and (max-width:768px) {
  #pgside { width: 70px; }
  #pgside #pguser { justify-content: center; }
  #pgside a {
    text-align: center;
    padding: 20px 0;
  }
  #pgside i.ico {
    font-size: 1.5em;
    margin-right: 0;
  }
  #pgside i.txt { display: none; }
}

/* (C) MAIN CONTENTS */
#pgmain {
  flex-grow: 1;
  padding: 20px;
  background: #f2f2f2;
}
main {
  margin: 0;
  padding: 5px;
  background-color: lightgray;
}

main > h1, p, .browser {
  margin: 10px;
  padding: 5px;
}

.browser {
  background: white;
}

.browser > h2, p {
  margin: 4px;
  font-size: 90%;
}
.b {
  background-color: #f44336;
  color: white;
  padding: 14px 25px;
  text-align: center;
  text-decoration: none;
  display: inline-block;
}

a:hover, a:active {
  background-color: red;
}
    </style>
</head>
<body>
   <!-- (A) SIDEBAR -->
   <div id="pgside">
    <!-- (A1) BRANDING OR USER -->
    <!-- LINK TO DASHBOARD OR LOGOUT -->
    <div id="pguser">
      <img src="potato.png"/>
      <i class="txt">MY ADMIN</i>
    </div>

    <!-- (A2) MENU ITEMS -->
    <a href="{% url 'perpustakaan:form_mhs' %}" >
      <i class="far fa-address-card">&#xf2bb;</i>
      <i class="txt">Mahasiswa</i>
    </a>
    <a href="{% url 'perpustakaan:formbuku'%}">
      <i class="ico">&#9728;</i>
      <i class="txt">Buku</i>
    </a>
    <a href="{% url 'perpustakaan:formpinjam'%}">
      <i class="ico">&#9738;</i>
      <i class="txt">Pinjaman</i>
    </a>
    <a href="{% url 'perpustakaan:daftar'%}">
      <i class="ico">&#9737;</i>
      <i class="txt">lihat Daftar</i>
    </a>
  </div>

  <main>
    <a class="b" href="{% url 'perpustakaan:list_buku'%}">daftar buku</a>
    <a class="b" href="{% url 'perpustakaan:list_mahasiswa'%}">daftar Mahasiswa</a>
    <a class="b" href="{% url 'perpustakaan:daftarpinjam'%}">daftar pinjaman</a>
  </main>
  

</body>
</html>

perpustakaan/templates/perpustakaan/editbuku.html
<!DOCTYPE html>
{% include "perpustakaan/navbar.html" %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <br><br>
    <center>
        <h3 class="p-3 mb-2 bg-success text-white" style='font-size: 30px;text-align:center;'>Ubah Data Buku</h3>
        <form method="POST">
            {% csrf_token %}
            <div class="container">
                <table class="table table-hover table-condensed table-striped table-bordered">
                    <tr>
                        <td>idbuku</td>
                        <td><input type="text" name="idbuku" value="{{editbuku.idbuku}}"></td>
                        <td>cover</td>
                    </tr>
                    <tr>
                        <td>judul</td>
                        <td><input type="text" name="judul" value="{{editbuku.judul}}"> </td>
                        <td rowspan="6" align="center"><img src="{{editbuku.cover.url}}" alt="connect" style="max-height:300px"></td>
                    </tr>
                    <tr>
                        <td>pengarang</td>
                        <td><input type="text" name="pengarang" value="{{editbuku.pengarang}}"></td>
                    </tr>
                    <tr>
                        <td>Kategori</td>
                        <td><input type="text" name="kategori" value="{{editbuku.kategori}}"></td>
                    </tr>
                    <tr>
                        <td>Sinopsis</td>
                        <td><input type="text" name="sinopsis" value="{{editbuku.sinopsis}}"></td>
                    </tr>
                    <tr>
                        <td>Tahun Terbit</td>
                        <td><input type="text" name="tahunterbit" value="{{editbuku.tahunterbit}}"></td>
                    </tr>
                    <tr>
                        <td>Penerbit</td>
                        <td><input type="text" name="penerbit" value="{{editbuku.penerbit}}"></td>
                    </tr>
                    <div class="links"></div>
                    <tr>
                        <td>OPSI</td>
                        <td><input type="submit" value="Simpan" onclick="return confirm('apakah anda yakin ingin mengubah')"> </td>
                    </tr>
                </table>
            </div>
        </form>
        {% if messages %}
        <ul class="alert alert-success">
            {% for message in messages %}
            <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} <a href="{% url 'perpustakaan:list_buku' %}">lihat</a></li>
            {% endfor %}
        </ul>
        {% endif %}
    </center>
    {% include "perpustakaan/footer.html" %}  
</body>

</html>

perpustakaan/templates/perpustakaan/navbar.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Perpus Kita</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <style type="text/css">
    .bs-example {
      margin: 0px;

    }

    .navbar-brand {
      font-size: 20px;
      font-family: sans-serif;
    }

    img {
      border-radius: 8px;
      width: 170px;
    }

    img.bg {
      position: relative;
      width: 100%;
    }

    .b {
      background-color: #f44336;
      color: white;
      padding: 5px 14px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      border-radius: 10px;
    }

    .e {
      background-color: #00740e;
      color: white;
      padding: 5px 14px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      border-radius: 10px;
    }

    .c {
      background-color: #00388d;
      color: white;
      padding: 5px 14px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      border-radius: 10px;
    }

    .ytm {
      position: absolute;
      top: 8%;
      width: 100%;
      height: 10cm;
      z-index: 4;
    }

    .yng{
    background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)) , url("{% static 'wp2.jpg' %}");
    height: 100vh;
    background-position: center center;
    background-size: cover;
    -webkit-background-sizi: cover;
    position: relative;

    }

  </style>
</head>

<body>

  <div class="bs-example">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
      <img src="{% static 'logo.png'%}" alt="">
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
        <div class="navbar-nav"></div>
        <div class="navbar-nav">
          <a href="#" class="nav-item nav-link active">{{user}}</a>
          <a href="/perpuskita" class="nav-item nav-link active">home</a>

          <!--for book dropdown button-->
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Buku</a>
            <div class="dropdown-menu">
              <a href="{% url 'perpustakaan:formbuku'%}" class="dropdown-item">Tambah Buku</a>
              <a href="{% url 'perpustakaan:list_buku'%}" class="dropdown-item">Daftar Buku</a>
            </div>
          </div>
          <!--for issuebook dropdown button-->
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Mahasiswa</a>
            <div class="dropdown-menu">
              <a href="{% url 'perpustakaan:formmhs' %}" class="dropdown-item">tambah Mahasiswa</a>
              <a href="{% url 'perpustakaan:list_mhs'%}" class="dropdown-item">Daftar Mahasiswa</a>
            </div>
          </div>

          <!--for student dropdown button-->
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pinjaman</a>
            <div class="dropdown-menu">
              <a href="{% url 'perpustakaan:formpinjam' %}" class="dropdown-item">Tambah Pinjaman</a>
              <a href="{% url 'perpustakaan:list_pinjam' %}" class="dropdown-item">Daftar Pinjaman</a>
            </div>
          </div>

          <div class="nav-item dropdown">
            <a href="{% url 'perpustakaan:logout' %}" class="nav-item nav-link active">Logout</a>
          </div>
        </div>




      </div>
    </nav>
  </div>


</body>

</html>

perpustakaan/templates/perpustakaan/navbaradmin.html
{% load static %}
<!DOCTYPE html>

<html lang="en">

<head>
  <meta charset="utf-8">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>Perpus Kita</title>
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

  <style type="text/css">
    .bs-example {
      margin: 0px;

    }

    .navbar-brand {
      font-size: 20px;
      font-family: sans-serif;
    }

    img {
      border-radius: 8px;
      width: 170px;
    }

    img.bg {
      position: relative;
      width: 100%;
    }

    .b {
      background-color: #f44336;
      color: white;
      padding: 5px 14px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      border-radius: 10px;
    }

    .e {
      background-color: #00740e;
      color: white;
      padding: 5px 14px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      border-radius: 10px;
    }

    .c {
      background-color: #00388d;
      color: white;
      padding: 5px 14px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
      border-radius: 10px;
    }

    .ytm {
      position: absolute;
      top: 8%;
      width: 100%;
      height: 10cm;
      z-index: 4;
    }

    .yng{
    background: linear-gradient(rgba(0,0,0,0.6), rgba(0,0,0,0.6)) , url("{% static 'wp2.jpg' %}");
    height: 100vh;
    background-position: center center;
    background-size: cover;
    -webkit-background-sizi: cover;
    position: relative;

    }

  </style>
</head>

<body>

  <div class="bs-example">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
      <img src="{% static 'logo.png'%}" alt="">
      <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
        <div class="navbar-nav"></div>
        <div class="navbar-nav">
          <a href="#" class="nav-item nav-link active">{{user}}</a>
          <a href="http://127.0.0.1:8000/admin" class="nav-item nav-link active">Menu Admin</a>

          <!--for book dropdown button-->
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Buku</a>
            <div class="dropdown-menu">
              <a href="{% url 'perpustakaan:formbuku'%}" class="dropdown-item">Tambah Buku</a>
              <a href="{% url 'perpustakaan:list_buku'%}" class="dropdown-item">Daftar Buku</a>
            </div>
          </div>
          <!--for issuebook dropdown button-->
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Mahasiswa</a>
            <div class="dropdown-menu">
              <a href="{% url 'perpustakaan:formmhs' %}" class="dropdown-item">tambah Mahasiswa</a>
              <a href="{% url 'perpustakaan:list_mhs'%}" class="dropdown-item">Daftar Mahasiswa</a>
            </div>
          </div>

          <!--for student dropdown button-->
          <div class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">Pinjaman</a>
            <div class="dropdown-menu">
              <a href="{% url 'perpustakaan:formpinjam' %}" class="dropdown-item">Tambah Pinjaman</a>
              <a href="{% url 'perpustakaan:list_pinjam' %}" class="dropdown-item">Daftar Pinjaman</a>
            </div>
          </div>

          <div class="nav-item dropdown">
            <a href="{% url 'perpustakaan:logout' %}" class="nav-item nav-link active">Logout</a>
          </div>
        </div>




      </div>
    </nav>
  </div>


</body>

</html>

perpustakaan/templates/perpustakaan/navlogin.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
<meta charset="utf-8">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Perpus Kita</title>
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>


<style type="text/css">
    .bs-example{
        margin: 0px;

    }
.navbar-brand{
  font-size: 20px;
  font-family: sans-serif;

}
img {
  border-radius: 8px;
  width: 170px;
}


</style>
</head>
<body>

<div class="bs-example">
    <nav class="navbar navbar-expand-md bg-dark navbar-dark fixed-top">
      <img src="{% static 'logo.png'%}" alt="">
        <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse justify-content-between" id="navbarCollapse">
            <div class="navbar-nav">
                


            </div>
            <div class="navbar-nav">
              <a href="/admin" class="nav-item nav-link active"></a>

                <div class="nav-item dropdown">
                  <a href="{% url 'perpustakaan:logout' %}" class="nav-item nav-link active" ></a>
                </div>
            </div>




        </div>
    </nav>
</div>


</body>
</html>